In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [45]:
#Importing the numpy library
import numpy as np
#Operating with Randomized Matrices

#I was thinking this program could be used as a way to practice operating 2 matrices
#First, the program would give two random matrices to work on and analyze
#Then the user could check their answers by choosing one of the given option

#Setting the 'while' loop
Repetition_27 = True 
while Repetition_27 == True:
    
#User input the size of the matrix
    print()
    a_27 = input("Matrix size:")

#Generating randomized matrices
    Matrix1_27 = np.random.randint(1,20, size=(int(a_27),int(a_27)))
    Matrix2_27 = np.random.randint(1,20, size=(int(a_27),int(a_27)))

#Printing randomized matrices for the user to see
    print("Randomized matrix 1:")
    print(Matrix1_27)
    print()
    print("Randomized matrix 2:")
    print(Matrix2_27)
    print()

#User is given the  option to generate another set of randomized matrices
    Repeat_27 = input("Do you wish to proceed with these matrices?[Y/N]")
    print()
    if(Repeat_27 == 'Y' or Repeat_27 == 'y'):
        break
        (Repetition_27 == False)
    
#Keeping the value of the matrices
KeepMatrix1_27 = Matrix1_27.copy()
KeepMatrix2_27 = Matrix2_27.copy()
print()

#Loop of list of operations
Repeeat_27 = True
while Repeeat_27 == True:
    print()
    print("[1]Information about Matrix 1")
    print("[2]Information about Matrix 2")
    print("[3]Transpose and inverse of Matrix 1")
    print("[4]Transpose and inverse of Matrix 2")
    print("[5]Sum of the two matrices")
    print("[6]Matrix 1 times Matrix 2")
    print("[7]Matrix 2 times Matrix 1")
    print("[8]Difference of the two matrices")
    print()
    Option_27 = input("Which one would you want to know?")

#Using if-else to do each function and display result

    if Option_27 == '1':
        print()
        print("Dimension: ")
        print(Matrix1_27.ndim)
        print("Shape: ")
        print(Matrix1_27.shape)
        print("Min: ")
        print(np.min(Matrix1_27))
        print("Max: ")
        print(np.max(Matrix1_27))
        print("Determinant: ")
        print(np.linalg.det(Matrix1_27))
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if (Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
            
    elif Option_27 == '2':
        print()
        print("Dimension: ")
        print(Matrix2_27.ndim)
        print("Shape: ")
        print(Matrix2_27.shape)
        print("Min: ")
        print(np.min(Matrix2_27))
        print("Max: ")
        print(np.max(Matrix2_27))
        print("Determinant: ")
        print(np.linalg.det(Matrix2_27))
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == "n"):
            break
            (Repeeat_27 == False)
            
    elif Option_27  == '3':
        print("Transpose: ")
        print(np.transpose(Matrix1_27))
        print("Inverse: ")
        print(np.linalg.inv(Matrix1_27))
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
            
    elif Option_27 == '4':
        print("Transpose: ")
        print(np.transpose(Matrix2_27))
        print("Inverse: ")
        print(np.linalg.inv(Matrix2_27))
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == "n"):
            break
            (Repeeat_27 == False)
        
    elif Option_27 == '5':
        print(Matrix1_27 + Matrix2_27)
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
            
    elif Option_27 == '6':
        print(np.dot(Matrix1_27, Matrix2_27))
        
        print()
        Answer = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
        
    elif Option_27 == '7':
        print(np.dot(Matrix2_27, Matrix1_27))
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
            
    elif Option_27 == '8':
        print(Matrix1_27 - Matrix2_27)
        
        print()
        Answer_27 = input("Would you like to know something else?[Y/N]")
        if(Answer_27 == 'N' or Answer_27 == 'n'):
            break
            (Repeeat_27 == False)
    
    else:
        print()
        print("There's no " + Option_27 + " in the options, you fool.")
        print("Try again.")
        
            
    


Matrix size: 3


Randomized matrix 1:
[[ 8 18 15]
 [ 1  4  6]
 [ 1 12  8]]

Randomized matrix 2:
[[ 1  2 11]
 [ 3  9  7]
 [ 5 19 14]]



Do you wish to proceed with these matrices?[Y/N] n


Matrix size: 2


Randomized matrix 1:
[[10 18]
 [ 6  7]]

Randomized matrix 2:
[[ 7  8]
 [ 3 13]]



Do you wish to proceed with these matrices?[Y/N] Y





[1]Information about Matrix 1
[2]Information about Matrix 2
[3]Transpose and inverse of Matrix 1
[4]Transpose and inverse of Matrix 2
[5]Sum of the two matrices
[6]Matrix 1 times Matrix 2
[7]Matrix 2 times Matrix 1
[8]Difference of the two matrices



Which one would you want to know? 3


Transpose: 
[[10  6]
 [18  7]]
Inverse: 
[[-0.18421053  0.47368421]
 [ 0.15789474 -0.26315789]]



Would you like to know something else?[Y/N] Y



[1]Information about Matrix 1
[2]Information about Matrix 2
[3]Transpose and inverse of Matrix 1
[4]Transpose and inverse of Matrix 2
[5]Sum of the two matrices
[6]Matrix 1 times Matrix 2
[7]Matrix 2 times Matrix 1
[8]Difference of the two matrices



Which one would you want to know? 6


[[124 314]
 [ 63 139]]



Would you like to know something else?[Y/N] Y



[1]Information about Matrix 1
[2]Information about Matrix 2
[3]Transpose and inverse of Matrix 1
[4]Transpose and inverse of Matrix 2
[5]Sum of the two matrices
[6]Matrix 1 times Matrix 2
[7]Matrix 2 times Matrix 1
[8]Difference of the two matrices



Which one would you want to know? 1



Dimension: 
2
Shape: 
(2, 2)
Min: 
6
Max: 
18
Determinant: 
-38.000000000000014



Would you like to know something else?[Y/N] Y



[1]Information about Matrix 1
[2]Information about Matrix 2
[3]Transpose and inverse of Matrix 1
[4]Transpose and inverse of Matrix 2
[5]Sum of the two matrices
[6]Matrix 1 times Matrix 2
[7]Matrix 2 times Matrix 1
[8]Difference of the two matrices



Which one would you want to know? 9



There's no 9 in the options, you fool.
Try again.

[1]Information about Matrix 1
[2]Information about Matrix 2
[3]Transpose and inverse of Matrix 1
[4]Transpose and inverse of Matrix 2
[5]Sum of the two matrices
[6]Matrix 1 times Matrix 2
[7]Matrix 2 times Matrix 1
[8]Difference of the two matrices



Which one would you want to know? 5


[[17 26]
 [ 9 20]]



Would you like to know something else?[Y/N] N


In [62]:
#Importing the numpy library
import numpy as np

#Creating an array from 1 to 10
Array_27 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

#Displaying array
print("Original array: ")
print(Array_27)

print()

#Raising the elements of the Array to the power of 3
print("Array elements raised to the power of 3: ")
NewArray_27 = np.power(Array_27, 3)
print(NewArray_27)

print()

#Taking elements from the new array
print(NewArray_27[2:])
print()
print(NewArray_27[:,1])
print()
print(NewArray_27[0,1:2])

Original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array elements raised to the power of 3: 
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]

[[343 512 729]]

[  8 125 512]

[8]


In [68]:
#Making Matrix with a pattern
#import numpy from library
import numpy as np

a = np.ones((3,3))
b = np.identity(3)*6
c = a + b
d[1:-1,1:-1] = c
print(d)

[[0. 0. 0. 0. 0.]
 [0. 7. 1. 1. 0.]
 [0. 1. 7. 1. 0.]
 [0. 1. 1. 7. 0.]
 [0. 0. 0. 0. 0.]]
